### PR TITLE
Expose per-channel metric information in wandb

### LINKED ISSUE #53: Log metrics by channel
Users have requested that the accuracy in each satellite channel is logged in the validation process

### PR DESCRIPTION
**Pull request by phinate**
Changes all metrics to not reduce over the channel dimension, and adds a new bar chart that summarises the per-channel average metrics.

Closes #53

### CODE REVIEW

**Comment by phinate** [comment]
I'll mark this ready for review once one of me, @dfulu or @IFenton tries this with wandb!

**Comment by dfulu** [comment]
> I'll mark this ready for review once one of me, @dfulu or @IFenton tries this with wandb!

I tried it with wandb and it looks fine -> https://wandb.ai/manchester_prize/cloudcasting/runs/9kp36mme

**Review by dfulu — APPROVED** [review]
Looks good to me :)

**Comment by phinate** [comment]
I don't have access to that weights & biases team @dfulu  - I just see a 404. Let's look at that outside of this PR and get it merged so people can use it!

**Comment by dfulu** [comment]
> I don't have access to that weights & biases team @dfulu - I just see a 404. Let's look at that outside of this PR and get it merged so people can use it!

@phinate I've made the team public so everyone should be able to see it now

**Comment by phinate** [comment]
Great! Looks smart, nice job team :)

image

**Pull request merged**
